---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
weather_df |>
  plot_ly(
    x = ~ name, y = ~tmax,
    type = "box", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
weather_df |>
  mutate(text_label = str_c("Name: ", name)) |>
  plot_ly(
    x = ~tmax, y = ~tmin, color = ~name,
    type = "scatter", mode = "markers"
  )
```

### Chart C

```{r}
weather_df |>
  plot_ly(
    x = ~name, y = ~prcp, 
    type = "bar")
```

